packages:
  - 'packages/*'

catalog:
  buffer: ^6.0.3
  events: ^3.3.0
  "tslib": ^2.8.1
  tsx: ^4.20.6
  typescript: ^5.9.3

catalogs:
  base64id:
    base64id: ^2.0.0
    "@types/base64id": ^2.0.2

  clone-deep:
    clone-deep: ^4.0.1
    "@types/clone-deep": ^4.0.4

  json-web-token:
    "@types/jsonwebtoken": ^9.0.10
    jsonwebtoken: ^9.0.2

  node:
    "@types/node": ^24.9.1

  rollup:
    "@kineticcafe/rollup-plugin-delete": ^3.0.2
    "@rollup/plugin-alias": ^5.1.1
    "@rollup/plugin-commonjs": ^28.0.8
    "@rollup/plugin-node-resolve": ^16.0.3
    "@rollup/plugin-terser": ^0.4.4
    "@rollup/plugin-typescript": ^11.1.6
    "rollup": ^4.52.5
    "rollup-plugin-dts": ^6.2.3

  secure-data-systems:
    "@secure-data-systems/eslint-config": 1.0.7
    "@secure-data-systems/tsconfig": 1.0.1

  ws:
    isomorphic-ws: ^5.0.0
    ws: ^8.18.3
    "@types/ws": ^8.18.1