packages:
  - 'config/*'
  - 'packages/*'
  - 'tests/*'

catalog:
  buffer: ^6.0.3
  events: ^3.3.0
  "tslib": ^2.8.1
  tsx: ^4.20.6
  turbo: ^2.6.1
  typescript: ^5.9.3

catalogs:
  base64id:
    base64id: ^2.0.0
    "@types/base64id": ^2.0.2

  clone-deep:
    clone-deep: ^4.0.1
    "@types/clone-deep": ^4.0.4

  json-web-token:
    "@types/jsonwebtoken": ^9.0.10
    jsonwebtoken: ^9.0.2

  node:
    "@types/node": ^24.10.1

  rollup:
    "@kineticcafe/rollup-plugin-delete": ^3.0.2
    "@rollup/plugin-alias": ^6.0.0
    "@rollup/plugin-commonjs": ^29.0.0
    "@rollup/plugin-node-resolve": ^16.0.3
    "@rollup/plugin-terser": ^0.4.4
    "@rollup/plugin-typescript": ^12.3.0
    "rollup": ^4.53.2
    "rollup-plugin-dts": ^6.2.3

  secure-data-systems:
    "@secure-data-systems/eslint-config": 1.0.26
    "@secure-data-systems/tsconfig": 1.0.2

  ws:
    isomorphic-ws: ^5.0.0
    ws: ^8.18.3
    "@types/ws": ^8.18.1